# Generated by Django 4.2.25 on 2025-10-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(choices=[('Standart', 'Стандарт'), ('Luxury', 'Люкс'), ('President', 'Президент')], max_length=64, unique=True, verbose_name='Название типа номера'),
        ),
    ]
