# Generated by Django 4.2.25 on 2025-10-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_roomtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('checked_out', 'Выселен'), ('checked_in', 'Заселен'), ('booked', 'Забронировано'), ('cancelled', 'Отменено')], default='Забронировано', max_length=64, verbose_name='Статус брони'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(choices=[('Standart', 'Стандарт'), ('Luxury', 'Люкс'), ('President', 'Президент')], default='', max_length=64, verbose_name='Название типа номера'),
        ),
    ]
