# Generated by Django 4.2.25 on 2025-10-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_alter_roomtype_unique_together_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_title'),
        ),
    ]
