# Generated by Django 4.2.25 on 2025-10-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_room_unique_title'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='room',
            name='unique_title',
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('title', 'room_type'), name='unique_title'),
        ),
    ]
