# Generated by Django 4.2.25 on 2025-11-10 11:07

from django.db import migrations, models
import django.db.models.deletion
import rooms.utils


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_alter_room_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Загрузите фотографию', upload_to=rooms.utils.room_image_upload_path, verbose_name='Фотография')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки фото')),
                ('room', models.ForeignKey(help_text='Номер к которому привязано фото', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.room', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Фотография номера',
                'verbose_name_plural': 'Фотографии номеров',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
