# Generated by Django 4.2.25 on 2025-11-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0014_roomimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название типа номера'),
        ),
    ]
