# Generated by Django 4.2.25 on 2025-10-18 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название типа номера')),
                ('description', models.TextField(blank=True, verbose_name='Описание типа номера')),
            ],
            options={
                'verbose_name': 'Тип номера',
                'verbose_name_plural': 'Типы номеров',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название номера')),
                ('description', models.TextField(blank=True, verbose_name='Описание номера')),
                ('is_avialible', models.BooleanField(default=True, verbose_name='Статус номера')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена за сутки')),
                ('capacity', models.PositiveSmallIntegerField(default=1, verbose_name='Вместимость')),
                ('number_of_rooms', models.PositiveSmallIntegerField(default=1, verbose_name='Количество комнат')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания номера')),
                ('room_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='rooms.roomtype', verbose_name='Тип номера')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
                'ordering': ['title', 'is_avialible'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Дата заезда')),
                ('check_out', models.DateField(verbose_name='Дата выселения')),
                ('status', models.CharField(choices=[('checked_out', 'Выселен'), ('checked_in', 'Заселен'), ('booked', 'Забронировано'), ('cancelled', 'Отменено')], default='Забронировано', max_length=64, verbose_name='Сттатус брони')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания бронирования')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
    ]
