# Generated by Django 4.2.25 on 2025-10-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_booking_status_alter_roomtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(choices=[('Standart', 'Стандарт'), ('Luxury', 'Люкс'), ('President', 'Президент')], default='Стандарт', max_length=64, verbose_name='Название типа номера'),
        ),
    ]
