# Generated by Django 4.2.25 on 2025-10-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_roomtype_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['title'], 'verbose_name': 'Номер', 'verbose_name_plural': 'Номера'},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='is_avialible',
            new_name='is_available',
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(choices=[('Standart', 'Стандарт'), ('Luxury', 'Люкс'), ('President', 'Президент')], default='Standart', max_length=64, verbose_name='Название типа номера'),
        ),
        migrations.AlterUniqueTogether(
            name='roomtype',
            unique_together={('name',)},
        ),
    ]
