# Generated by Django 4.2.25 on 2025-10-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomtype',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('checked_out', 'Выселен'), ('checked_in', 'Заселен'), ('booked', 'Забронировано'), ('cancelled', 'Отменено')], default='booked', max_length=64, verbose_name='Статус брони'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Цена за сутки'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['booked', 'checked_in'])), fields=('room', 'check_in', 'check_out'), name='unique_booking_period'),
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
    ]
