# Generated by Django 4.2.25 on 2025-11-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_alter_booking_room_alter_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(verbose_name='Статус номера'),
        ),
    ]
